USE Patients;
/***************************************************
-- Analyzing Patients table
****************************************************/
SELECT * FROM Patients;

SELECT 
	COUNT(ID) AS [TOTAL RECORDS],
	(SELECT COUNT(ID) FROM Patients WHERE ID = '') AS [BLANK COUNT],
	(SELECT COUNT(ID) FROM Patients WHERE ID IS NULL) AS [NULL COUNT],
	MIN(ID) AS [LOW VALUE],
	MAX(ID) AS [HIGH VALUE],
	MIN(LEN(ID)) AS [MINIMUM LENGTH],
	MAX(LEN(ID)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ID) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Patients GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ID) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Patients GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--Email
SELECT 
	COUNT(Email) AS [TOTAL RECORDS],
	(SELECT COUNT(Email) FROM Patients WHERE Email = '') AS [BLANK COUNT],
	(SELECT COUNT(Email) FROM Patients WHERE Email IS NULL) AS [NULL COUNT],
	MIN(Email) AS [LOW VALUE],
	MAX(Email) AS [HIGH VALUE],
	MIN(LEN(Email)) AS [MINIMUM LENGTH],
	MAX(LEN(Email)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Email) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Email) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Email HAVING COUNT(Email) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Email) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Email) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Email HAVING COUNT(Email) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--First Name
SELECT 
	COUNT(Fname) AS [TOTAL RECORDS],
	(SELECT COUNT(Fname) FROM Patients WHERE Fname = '') AS [BLANK COUNT],
	(SELECT COUNT(Fname) FROM Patients WHERE Fname IS NULL) AS [NULL COUNT],
	MIN(Fname) AS [LOW VALUE],
	MAX(Fname) AS [HIGH VALUE],
	MIN(LEN(Fname)) AS [MINIMUM LENGTH],
	MAX(LEN(Fname)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Fname) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Fname) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Fname HAVING COUNT(Fname) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Fname) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Fname) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Fname HAVING COUNT(Fname) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--Last Name
SELECT 
	COUNT(LName) AS [TOTAL RECORDS],
	(SELECT COUNT(LName) FROM Patients WHERE LName = '') AS [BLANK COUNT],
	(SELECT COUNT(LName) FROM Patients WHERE LName IS NULL) AS [NULL COUNT],
	MIN(LName) AS [LOW VALUE],
	MAX(LName) AS [HIGH VALUE],
	MIN(LEN(LName)) AS [MINIMUM LENGTH],
	MAX(LEN(LName)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT LName) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(LName) AS [TOTAL DUPLICATES] FROM Patients GROUP BY LName HAVING COUNT(LName) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(LName) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(LName) AS [TOTAL DUPLICATES] FROM Patients GROUP BY LName HAVING COUNT(LName) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--Address
SELECT 
	COUNT(Address) AS [TOTAL RECORDS],
	(SELECT COUNT(Address) FROM Patients WHERE Address = '') AS [BLANK COUNT],
	(SELECT COUNT(Address) FROM Patients WHERE Address IS NULL) AS [NULL COUNT],
	MIN(Address) AS [LOW VALUE],
	MAX(Address) AS [HIGH VALUE],
	MIN(LEN(Address)) AS [MINIMUM LENGTH],
	MAX(LEN(Address)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Address) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Address) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Address HAVING COUNT(Address) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Address) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Address) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Address HAVING COUNT(Address) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--City
SELECT 
	COUNT(City) AS [TOTAL RECORDS],
	(SELECT COUNT(City) FROM Patients WHERE City = '') AS [BLANK COUNT],
	(SELECT COUNT(City) FROM Patients WHERE City IS NULL) AS [NULL COUNT],
	MIN(City) AS [LOW VALUE],
	MAX(City) AS [HIGH VALUE],
	MIN(LEN(City)) AS [MINIMUM LENGTH],
	MAX(LEN(City)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT City) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(City) AS [TOTAL DUPLICATES] FROM Patients GROUP BY City HAVING COUNT(City) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(City) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(City) AS [TOTAL DUPLICATES] FROM Patients GROUP BY City HAVING COUNT(City) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--State
SELECT 
	COUNT(State) AS [TOTAL RECORDS],
	(SELECT COUNT(State) FROM Patients WHERE State = '') AS [BLANK COUNT],
	(SELECT COUNT(State) FROM Patients WHERE State IS NULL) AS [NULL COUNT],
	MIN(State) AS [LOW VALUE],
	MAX(State) AS [HIGH VALUE],
	MIN(LEN(State)) AS [MINIMUM LENGTH],
	MAX(LEN(State)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT State) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(State) AS [TOTAL DUPLICATES] FROM Patients GROUP BY State HAVING COUNT(State) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(State) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(State) AS [TOTAL DUPLICATES] FROM Patients GROUP BY State HAVING COUNT(State) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--ZipCode
SELECT 
	COUNT(ZipCode) AS [TOTAL RECORDS],
	(SELECT COUNT(ZipCode) FROM Patients WHERE ZipCode = '') AS [BLANK COUNT],
	(SELECT COUNT(ZipCode) FROM Patients WHERE ZipCode IS NULL) AS [NULL COUNT],
	MIN(ZipCode) AS [LOW VALUE],
	MAX(ZipCode) AS [HIGH VALUE],
	MIN(LEN(ZipCode)) AS [MINIMUM LENGTH],
	MAX(LEN(ZipCode)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ZipCode) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ZipCode) AS [TOTAL DUPLICATES] FROM Patients GROUP BY ZipCode HAVING COUNT(ZipCode) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ZipCode) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ZipCode) AS [TOTAL DUPLICATES] FROM Patients GROUP BY ZipCode HAVING COUNT(ZipCode) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

/***************************************************
-- Table: Clinic
****************************************************/
SELECT * FROM Clinics;

SELECT
    'Clinics' as [TABLE NAME],
	'ID' as [COLUMN NAME], 
	COUNT(ID) AS [TOTAL RECORDS],
	(SELECT COUNT(ID) FROM Clinics WHERE ID = '') AS [BLANK COUNT],
	(SELECT COUNT(ID) FROM Clinics WHERE ID IS NULL) AS [NULL COUNT],
	MIN(ID) AS [LOW VALUE],
	MAX(ID) AS [HIGH VALUE],
	MIN(LEN(ID)) AS [MINIMUM LENGTH],
	MAX(LEN(ID)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ID) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ID) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Clinics;

SELECT
    'Clinics' as [TABLE NAME],
	'Name' as [COLUMN NAME], 
	COUNT(Name) AS [TOTAL RECORDS],
	(SELECT COUNT(Name) FROM Clinics WHERE Name = '') AS [BLANK COUNT],
	(SELECT COUNT(Name) FROM Clinics WHERE Name IS NULL) AS [NULL COUNT],
	MIN(Name) AS [LOW VALUE],
	MAX(Name) AS [HIGH VALUE],
	MIN(LEN(Name)) AS [MINIMUM LENGTH],
	MAX(LEN(Name)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Name) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Name) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY Name HAVING COUNT(Name) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Name) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Name) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY Name HAVING COUNT(Name) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Clinics;

SELECT
    'Clinics' as [TABLE NAME],
	'Address' as [COLUMN NAME], 
	COUNT(Address) AS [TOTAL RECORDS],
	(SELECT COUNT(Address) FROM Clinics WHERE Address = '') AS [BLANK COUNT],
	(SELECT COUNT(Address) FROM Clinics WHERE Address IS NULL) AS [NULL COUNT],
	MIN(Address) AS [LOW VALUE],
	MAX(Address) AS [HIGH VALUE],
	MIN(LEN(Address)) AS [MINIMUM LENGTH],
	MAX(LEN(Address)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Address) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Address) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY Address HAVING COUNT(Address) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Address) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Address) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY Address HAVING COUNT(Address) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Clinics;

SELECT
    'Clinics' as [TABLE NAME],
	'City' as [COLUMN NAME], 
	COUNT(City) AS [TOTAL RECORDS],
	(SELECT COUNT(City) FROM Clinics WHERE City = '') AS [BLANK COUNT],
	(SELECT COUNT(City) FROM Clinics WHERE City IS NULL) AS [NULL COUNT],
	MIN(City) AS [LOW VALUE],
	MAX(City) AS [HIGH VALUE],
	MIN(LEN(City)) AS [MINIMUM LENGTH],
	MAX(LEN(City)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT City) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(City) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY City HAVING COUNT(City) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(City) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(City) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY City HAVING COUNT(City) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Clinics;


