USE Patients;
/***************************************************
-- Analyzing Patients table
****************************************************/
SELECT * FROM Patients;

SELECT 
	COUNT(ID) AS [TOTAL RECORDS],
	(SELECT COUNT(ID) FROM Patients WHERE ID = '') AS [BLANK COUNT],
	(SELECT COUNT(ID) FROM Patients WHERE ID IS NULL) AS [NULL COUNT],
	MIN(ID) AS [LOW VALUE],
	MAX(ID) AS [HIGH VALUE],
	MIN(LEN(ID)) AS [MINIMUM LENGTH],
	MAX(LEN(ID)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ID) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Patients GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ID) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Patients GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--Email
SELECT 
	COUNT(Email) AS [TOTAL RECORDS],
	(SELECT COUNT(Email) FROM Patients WHERE Email = '') AS [BLANK COUNT],
	(SELECT COUNT(Email) FROM Patients WHERE Email IS NULL) AS [NULL COUNT],
	MIN(Email) AS [LOW VALUE],
	MAX(Email) AS [HIGH VALUE],
	MIN(LEN(Email)) AS [MINIMUM LENGTH],
	MAX(LEN(Email)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Email) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Email) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Email HAVING COUNT(Email) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Email) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Email) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Email HAVING COUNT(Email) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--First Name
SELECT 
	COUNT(Fname) AS [TOTAL RECORDS],
	(SELECT COUNT(Fname) FROM Patients WHERE Fname = '') AS [BLANK COUNT],
	(SELECT COUNT(Fname) FROM Patients WHERE Fname IS NULL) AS [NULL COUNT],
	MIN(Fname) AS [LOW VALUE],
	MAX(Fname) AS [HIGH VALUE],
	MIN(LEN(Fname)) AS [MINIMUM LENGTH],
	MAX(LEN(Fname)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Fname) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Fname) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Fname HAVING COUNT(Fname) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Fname) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Fname) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Fname HAVING COUNT(Fname) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--Last Name
SELECT 
	COUNT(LName) AS [TOTAL RECORDS],
	(SELECT COUNT(LName) FROM Patients WHERE LName = '') AS [BLANK COUNT],
	(SELECT COUNT(LName) FROM Patients WHERE LName IS NULL) AS [NULL COUNT],
	MIN(LName) AS [LOW VALUE],
	MAX(LName) AS [HIGH VALUE],
	MIN(LEN(LName)) AS [MINIMUM LENGTH],
	MAX(LEN(LName)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT LName) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(LName) AS [TOTAL DUPLICATES] FROM Patients GROUP BY LName HAVING COUNT(LName) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(LName) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(LName) AS [TOTAL DUPLICATES] FROM Patients GROUP BY LName HAVING COUNT(LName) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--Address
SELECT 
	COUNT(Address) AS [TOTAL RECORDS],
	(SELECT COUNT(Address) FROM Patients WHERE Address = '') AS [BLANK COUNT],
	(SELECT COUNT(Address) FROM Patients WHERE Address IS NULL) AS [NULL COUNT],
	MIN(Address) AS [LOW VALUE],
	MAX(Address) AS [HIGH VALUE],
	MIN(LEN(Address)) AS [MINIMUM LENGTH],
	MAX(LEN(Address)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Address) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Address) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Address HAVING COUNT(Address) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Address) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Address) AS [TOTAL DUPLICATES] FROM Patients GROUP BY Address HAVING COUNT(Address) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--City
SELECT 
	COUNT(City) AS [TOTAL RECORDS],
	(SELECT COUNT(City) FROM Patients WHERE City = '') AS [BLANK COUNT],
	(SELECT COUNT(City) FROM Patients WHERE City IS NULL) AS [NULL COUNT],
	MIN(City) AS [LOW VALUE],
	MAX(City) AS [HIGH VALUE],
	MIN(LEN(City)) AS [MINIMUM LENGTH],
	MAX(LEN(City)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT City) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(City) AS [TOTAL DUPLICATES] FROM Patients GROUP BY City HAVING COUNT(City) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(City) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(City) AS [TOTAL DUPLICATES] FROM Patients GROUP BY City HAVING COUNT(City) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--State
SELECT 
	COUNT(State) AS [TOTAL RECORDS],
	(SELECT COUNT(State) FROM Patients WHERE State = '') AS [BLANK COUNT],
	(SELECT COUNT(State) FROM Patients WHERE State IS NULL) AS [NULL COUNT],
	MIN(State) AS [LOW VALUE],
	MAX(State) AS [HIGH VALUE],
	MIN(LEN(State)) AS [MINIMUM LENGTH],
	MAX(LEN(State)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT State) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(State) AS [TOTAL DUPLICATES] FROM Patients GROUP BY State HAVING COUNT(State) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(State) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(State) AS [TOTAL DUPLICATES] FROM Patients GROUP BY State HAVING COUNT(State) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

--ZipCode
SELECT 
	COUNT(ZipCode) AS [TOTAL RECORDS],
	(SELECT COUNT(ZipCode) FROM Patients WHERE ZipCode = '') AS [BLANK COUNT],
	(SELECT COUNT(ZipCode) FROM Patients WHERE ZipCode IS NULL) AS [NULL COUNT],
	MIN(ZipCode) AS [LOW VALUE],
	MAX(ZipCode) AS [HIGH VALUE],
	MIN(LEN(ZipCode)) AS [MINIMUM LENGTH],
	MAX(LEN(ZipCode)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ZipCode) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ZipCode) AS [TOTAL DUPLICATES] FROM Patients GROUP BY ZipCode HAVING COUNT(ZipCode) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ZipCode) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ZipCode) AS [TOTAL DUPLICATES] FROM Patients GROUP BY ZipCode HAVING COUNT(ZipCode) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Patients;

/***************************************************
-- Table: Clinic
****************************************************/
SELECT * FROM Clinics;

SELECT
    'Clinics' as [TABLE NAME],
	'ID' as [COLUMN NAME], 
	COUNT(ID) AS [TOTAL RECORDS],
	(SELECT COUNT(ID) FROM Clinics WHERE ID = '') AS [BLANK COUNT],
	(SELECT COUNT(ID) FROM Clinics WHERE ID IS NULL) AS [NULL COUNT],
	MIN(ID) AS [LOW VALUE],
	MAX(ID) AS [HIGH VALUE],
	MIN(LEN(ID)) AS [MINIMUM LENGTH],
	MAX(LEN(ID)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ID) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ID) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Clinics;

SELECT
    'Clinics' as [TABLE NAME],
	'Name' as [COLUMN NAME], 
	COUNT(Name) AS [TOTAL RECORDS],
	(SELECT COUNT(Name) FROM Clinics WHERE Name = '') AS [BLANK COUNT],
	(SELECT COUNT(Name) FROM Clinics WHERE Name IS NULL) AS [NULL COUNT],
	MIN(Name) AS [LOW VALUE],
	MAX(Name) AS [HIGH VALUE],
	MIN(LEN(Name)) AS [MINIMUM LENGTH],
	MAX(LEN(Name)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Name) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Name) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY Name HAVING COUNT(Name) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Name) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Name) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY Name HAVING COUNT(Name) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Clinics;

SELECT
    'Clinics' as [TABLE NAME],
	'Address' as [COLUMN NAME], 
	COUNT(Address) AS [TOTAL RECORDS],
	(SELECT COUNT(Address) FROM Clinics WHERE Address = '') AS [BLANK COUNT],
	(SELECT COUNT(Address) FROM Clinics WHERE Address IS NULL) AS [NULL COUNT],
	MIN(Address) AS [LOW VALUE],
	MAX(Address) AS [HIGH VALUE],
	MIN(LEN(Address)) AS [MINIMUM LENGTH],
	MAX(LEN(Address)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Address) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Address) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY Address HAVING COUNT(Address) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Address) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Address) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY Address HAVING COUNT(Address) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Clinics;

SELECT
    'Clinics' as [TABLE NAME],
	'City' as [COLUMN NAME], 
	COUNT(City) AS [TOTAL RECORDS],
	(SELECT COUNT(City) FROM Clinics WHERE City = '') AS [BLANK COUNT],
	(SELECT COUNT(City) FROM Clinics WHERE City IS NULL) AS [NULL COUNT],
	MIN(City) AS [LOW VALUE],
	MAX(City) AS [HIGH VALUE],
	MIN(LEN(City)) AS [MINIMUM LENGTH],
	MAX(LEN(City)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT City) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(City) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY City HAVING COUNT(City) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(City) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(City) AS [TOTAL DUPLICATES] FROM Clinics GROUP BY City HAVING COUNT(City) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Clinics;

/***************************************************
-- Table: Doctors
****************************************************/
SELECT * FROM Doctors;

SELECT
    'Doctors' as [TABLE NAME],
	'ID' as [COLUMN NAME], 
	COUNT(ID) AS [TOTAL RECORDS],
	(SELECT COUNT(ID) FROM Doctors WHERE ID = '') AS [BLANK COUNT],
	(SELECT COUNT(ID) FROM Doctors WHERE ID IS NULL) AS [NULL COUNT],
	MIN(ID) AS [LOW VALUE],
	MAX(ID) AS [HIGH VALUE],
	MIN(LEN(ID)) AS [MINIMUM LENGTH],
	MAX(LEN(ID)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ID) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Doctors GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ID) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Doctors GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Doctors;

SELECT
    'Doctors' as [TABLE NAME],
	'FName' as [COLUMN NAME], 
	COUNT(FName) AS [TOTAL RECORDS],
	(SELECT COUNT(FName) FROM Doctors WHERE FName = '') AS [BLANK COUNT],
	(SELECT COUNT(FName) FROM Doctors WHERE FName IS NULL) AS [NULL COUNT],
	MIN(FName) AS [LOW VALUE],
	MAX(FName) AS [HIGH VALUE],
	MIN(LEN(FName)) AS [MINIMUM LENGTH],
	MAX(LEN(FName)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT FName) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(FName) AS [TOTAL DUPLICATES] FROM Doctors GROUP BY FName HAVING COUNT(FName) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(FName) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(FName) AS [TOTAL DUPLICATES] FROM Doctors GROUP BY FName HAVING COUNT(FName) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Doctors;

SELECT
    'Doctors' as [TABLE NAME],
	'LName' as [COLUMN NAME], 
	COUNT(LName) AS [TOTAL RECORDS],
	(SELECT COUNT(LName) FROM Doctors WHERE LName = '') AS [BLANK COUNT],
	(SELECT COUNT(LName) FROM Doctors WHERE LName IS NULL) AS [NULL COUNT],
	MIN(LName) AS [LOW VALUE],
	MAX(LName) AS [HIGH VALUE],
	MIN(LEN(LName)) AS [MINIMUM LENGTH],
	MAX(LEN(LName)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT LName) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(LName) AS [TOTAL DUPLICATES] FROM Doctors GROUP BY LName HAVING COUNT(LName) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(LName) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(LName) AS [TOTAL DUPLICATES] FROM Doctors GROUP BY LName HAVING COUNT(LName) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Doctors;

/***************************************************
-- Table: Procedures
****************************************************/
SELECT * FROM Procedures;

SELECT
    'Procedures' as [TABLE NAME],
	'ID' as [COLUMN NAME], 
	COUNT(ID) AS [TOTAL RECORDS],
	(SELECT COUNT(ID) FROM Procedures WHERE ID = '') AS [BLANK COUNT],
	(SELECT COUNT(ID) FROM Procedures WHERE ID IS NULL) AS [NULL COUNT],
	MIN(ID) AS [LOW VALUE],
	MAX(ID) AS [HIGH VALUE],
	MIN(LEN(ID)) AS [MINIMUM LENGTH],
	MAX(LEN(ID)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ID) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Procedures GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ID) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Procedures GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Procedures;

SELECT
    'Procedures' as [TABLE NAME],
	'Name' as [COLUMN NAME], 
	COUNT(Name) AS [TOTAL RECORDS],
	(SELECT COUNT(Name) FROM Procedures WHERE Name = '') AS [BLANK COUNT],
	(SELECT COUNT(Name) FROM Procedures WHERE Name IS NULL) AS [NULL COUNT],
	MIN(Name) AS [LOW VALUE],
	MAX(Name) AS [HIGH VALUE],
	MIN(LEN(Name)) AS [MINIMUM LENGTH],
	MAX(LEN(Name)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Name) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Name) AS [TOTAL DUPLICATES] FROM Procedures GROUP BY Name HAVING COUNT(Name) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Name) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Name) AS [TOTAL DUPLICATES] FROM Procedures GROUP BY Name HAVING COUNT(Name) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Procedures;

SELECT
    'Procedures' as [TABLE NAME],
	'[Desc]' as [COLUMN NAME], 
	COUNT([Desc]) AS [TOTAL RECORDS],
	(SELECT COUNT([Desc]) FROM Procedures WHERE [Desc] = '') AS [BLANK COUNT],
	(SELECT COUNT([Desc]) FROM Procedures WHERE [Desc] IS NULL) AS [NULL COUNT],
	MIN([Desc]) AS [LOW VALUE],
	MAX([Desc]) AS [HIGH VALUE],
	MIN(LEN([Desc])) AS [MINIMUM LENGTH],
	MAX(LEN([Desc])) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT [Desc]) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT([Desc]) AS [TOTAL DUPLICATES] FROM Procedures GROUP BY [Desc] HAVING COUNT([Desc]) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT([Desc]) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT([Desc]) AS [TOTAL DUPLICATES] FROM Procedures GROUP BY [Desc] HAVING COUNT([Desc]) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Procedures;

SELECT
    'Procedures' as [TABLE NAME],
	'Charge' as [COLUMN NAME], 
	COUNT(Charge) AS [TOTAL RECORDS],
	(SELECT COUNT(Charge) FROM Procedures WHERE Charge = '') AS [BLANK COUNT],
	(SELECT COUNT(Charge) FROM Procedures WHERE Charge IS NULL) AS [NULL COUNT],
	MIN(Charge) AS [LOW VALUE],
	MAX(Charge) AS [HIGH VALUE],
	MIN(LEN(Charge)) AS [MINIMUM LENGTH],
	MAX(LEN(Charge)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Charge) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Charge) AS [TOTAL DUPLICATES] FROM Procedures GROUP BY Charge HAVING COUNT(Charge) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Charge) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Charge) AS [TOTAL DUPLICATES] FROM Procedures GROUP BY Charge HAVING COUNT(Charge) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Procedures;


/***************************************************
-- Table: Visits
****************************************************/
SELECT * FROM Visits;

SELECT
    'Visits' as [TABLE NAME],
	'ID' as [COLUMN NAME], 
	COUNT(ID) AS [TOTAL RECORDS],
	(SELECT COUNT(ID) FROM Visits WHERE ID = '') AS [BLANK COUNT],
	(SELECT COUNT(ID) FROM Visits WHERE ID IS NULL) AS [NULL COUNT],
	MIN(ID) AS [LOW VALUE],
	MAX(ID) AS [HIGH VALUE],
	MIN(LEN(ID)) AS [MINIMUM LENGTH],
	MAX(LEN(ID)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT ID) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Visits GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(ID) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(ID) AS [TOTAL DUPLICATES] FROM Visits GROUP BY ID HAVING COUNT(ID) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Visits;

SELECT
    'Visits' as [TABLE NAME],
	'Date' as [COLUMN NAME], 
	COUNT(Date) AS [TOTAL RECORDS],
	(SELECT COUNT(Date) FROM Visits WHERE Date = '') AS [BLANK COUNT],
	(SELECT COUNT(Date) FROM Visits WHERE Date IS NULL) AS [NULL COUNT],
	MIN(Date) AS [LOW VALUE],
	MAX(Date) AS [HIGH VALUE],
	MIN(LEN(Date)) AS [MINIMUM LENGTH],
	MAX(LEN(Date)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Date) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Date) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Date HAVING COUNT(Date) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Date) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Date) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Date HAVING COUNT(Date) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Visits;

SELECT
    'Visits' as [TABLE NAME],
	'Clinic' as [COLUMN NAME], 
	COUNT(Clinic) AS [TOTAL RECORDS],
	(SELECT COUNT(Clinic) FROM Visits WHERE Clinic = '') AS [BLANK COUNT],
	(SELECT COUNT(Clinic) FROM Visits WHERE Clinic IS NULL) AS [NULL COUNT],
	MIN(Clinic) AS [LOW VALUE],
	MAX(Clinic) AS [HIGH VALUE],
	MIN(LEN(Clinic)) AS [MINIMUM LENGTH],
	MAX(LEN(Clinic)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Clinic) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Clinic) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Clinic HAVING COUNT(Clinic) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Clinic) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Clinic) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Clinic HAVING COUNT(Clinic) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Visits;

SELECT
    'Visits' as [TABLE NAME],
	'Patient' as [COLUMN NAME], 
	COUNT(Patient) AS [TOTAL RECORDS],
	(SELECT COUNT(Patient) FROM Visits WHERE Patient = '') AS [BLANK COUNT],
	(SELECT COUNT(Patient) FROM Visits WHERE Patient IS NULL) AS [NULL COUNT],
	MIN(Patient) AS [LOW VALUE],
	MAX(Patient) AS [HIGH VALUE],
	MIN(LEN(Patient)) AS [MINIMUM LENGTH],
	MAX(LEN(Patient)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Patient) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Patient) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Patient HAVING COUNT(Patient) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Patient) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Patient) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Patient HAVING COUNT(Patient) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Visits;

SELECT
    'Visits' as [TABLE NAME],
	'Doctor' as [COLUMN NAME], 
	COUNT(Doctor) AS [TOTAL RECORDS],
	(SELECT COUNT(Doctor) FROM Visits WHERE Doctor = '') AS [BLANK COUNT],
	(SELECT COUNT(*) - COUNT(Doctor) FROM Visits) AS [NULL COUNT],
	MIN(Doctor) AS [LOW VALUE],
	MAX(Doctor) AS [HIGH VALUE],
	MIN(LEN(Doctor)) AS [MINIMUM LENGTH],
	MAX(LEN(Doctor)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Doctor) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Doctor) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Doctor HAVING COUNT(Doctor) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Doctor) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Doctor) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Doctor HAVING COUNT(Doctor) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Visits;

SELECT
    'Visits' as [TABLE NAME],
	'Charge' as [COLUMN NAME], 
	COUNT(Charge) AS [TOTAL RECORDS],
	(SELECT COUNT(Charge) FROM Visits WHERE Charge = '') AS [BLANK COUNT],
	(SELECT COUNT(Charge) FROM Visits WHERE Charge IS NULL) AS [NULL COUNT],
	MIN(Charge) AS [LOW VALUE],
	MAX(Charge) AS [HIGH VALUE],
	MIN(LEN(Charge)) AS [MINIMUM LENGTH],
	MAX(LEN(Charge)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Charge) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Charge) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Charge HAVING COUNT(Charge) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Charge) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Charge) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Charge HAVING COUNT(Charge) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Visits;

SELECT
    'Visits' as [TABLE NAME],
	'Charge' as [COLUMN NAME], 
	COUNT(Charge) AS [TOTAL RECORDS],
	(SELECT COUNT(Charge) FROM Visits WHERE Charge = '') AS [BLANK COUNT],
	(SELECT COUNT(Charge) FROM Visits WHERE Charge IS NULL) AS [NULL COUNT],
	MIN(Charge) AS [LOW VALUE],
	MAX(Charge) AS [HIGH VALUE],
	MIN(LEN(Charge)) AS [MINIMUM LENGTH],
	MAX(LEN(Charge)) AS [MAXIMUM LENGTH],
	COUNT(DISTINCT Charge) AS [NUMBER OF DISTINCT VALUES],
	(SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Charge) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Charge HAVING COUNT(Charge) > 1)  AS TBL) AS [DUPLICATED VALUES],
	COUNT(Charge) - (SELECT SUM(TBL.[TOTAL DUPLICATES]) FROM (SELECT COUNT(Charge) AS [TOTAL DUPLICATES] FROM Visits GROUP BY Charge HAVING COUNT(Charge) > 1)  AS TBL) AS [UNIQUE VALUES]
FROM Visits;

